// ================================================================
//  products-data.js  —  Janish Enterprises
//  Generated by Admin Panel on 14/4/2026
// ================================================================

const brandInfo = {
    "Kapson": {
        "name": "Kapson",
        "tagline": "Grease Pumps & Hydraulic Equipment",
        "description": "Kapson is one of India's leading manufacturers of grease pumps and lubrication equipment. Janish Enterprises is an authorised dealer for Kapson products.",
        "icon": "fas fa-oil-can",
        "logo": "images/kapson/logo.png"
    },
    "Penta": {
        "name": "Penta",
        "tagline": "Pneumatic Pumps & Grease Dispensers",
        "description": "Penta offers a wide range of pneumatic grease pumps and dispensers for heavy-duty industrial and automotive use. We are an authorised Penta dealer.",
        "icon": "fas fa-compress-alt",
        "logo": "images/brand1.png"
    },
    "Titan": {
        "name": "Titan",
        "tagline": "Hydraulic Jacks & Lifting Equipment",
        "description": "Titan hydraulic jacks are built for strength and reliability. From bottle jacks to trolley jacks, we stock the full Titan range.",
        "icon": "fas fa-car-side",
        "logo": "images/brand3.png"
    },
    "Groz": {
        "name": "Groz",
        "tagline": "Professional Hand Tools & Accessories",
        "description": "Groz manufactures precision hand tools used by professionals worldwide. We stock a wide range of Groz spanners, wrenches, and workshop accessories.",
        "icon": "fas fa-tools",
        "logo": "images/brand6.png"
    },
    "Hand Tools": {
        "name": "Hand Tools",
        "tagline": "Spanners, Wrenches & Workshop Tools",
        "description": "A wide selection of hand tools from trusted brands. Everything a mechanic needs for daily workshop use.",
        "icon": "fas fa-wrench",
        "logo": ""
    },
    "Power Tools": {
        "name": "Power Tools",
        "tagline": "Drills, Grinders & Impact Tools",
        "description": "Professional power tools for heavy-duty workshop use. Built to last, priced to be fair.",
        "icon": "fas fa-bolt",
        "logo": ""
    }
};

const productData = [
    {
        "id": 1,
        "name": "Hydraulic Bottle Jack",
        "brand": "Kapson",
        "description": "Kapson hydraulic bottle jack with heavy-duty steel base. Solid build with safety overload protection. Ideal for cars, SUVs, and light trucks.",
        "images": [
            "images/kapson/hydjack/k_902.png",
            "images/kapson/hydjack/k_910.png"
        ],
        "bestSeller": true,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "Model- K902 2 Ton",
                "price": 650
            },
            {
                "label": "Model- K904 4 Ton",
                "price": 800
            },
            {
                "label": "Model- K906 6 Ton",
                "price": 900
            },
            {
                "label": "Model- K910 10 Ton",
                "price": 1100
            },
            {
                "label": "Model- K912 12 Ton",
                "price": 1500
            },
            {
                "label": "Model- K916 16 Ton",
                "price": 1650
            },
            {
                "label": "Model- K920 20 Ton",
                "price": 1800
            },
            {
                "label": "Model- K935 35 Ton",
                "price": 2000
            },
            {
                "label": "Model- K950 50 Ton",
                "price": 2500
            },
            {
                "label": "Model- K975 75 Ton",
                "price": 2700
            },
            {
                "label": "Model- K900 100 Ton",
                "price": 3000
            }
        ]
    },
    {
        "id": 2,
        "name": "Grease Bucket Pump (Without Wheel)",
        "brand": "Kapson",
        "description": "Kapson grease bucket pump without wheel. Consistent pressure output for daily lubrication tasks in small to medium workshops.",
        "images": [
            "images/kapson/bgp/K-700.png",
            "images/kapson/bgp/K-701.png"
        ],
        "bestSeller": true,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "Model- K700 3kg BGP (w/o wheel)",
                "price": 1900
            },
            {
                "label": "Model- K701 5kg BGP (w/o wheel)",
                "price": 2100
            },
            {
                "label": "Model- KGP-6 6kg BGP (w/o wheel)",
                "price": 2300
            },
            {
                "label": "Model- K702 10kg BGP (w/o wheel)",
                "price": 2600
            }
        ]
    },
    {
        "id": 3,
        "name": "Grease Bucket Pump (With Wheel)",
        "brand": "Kapson",
        "description": "Kapson grease bucket pump on wheeled trolley for easy mobility. Durable steel construction. Available in multiple capacities.",
        "images": [
            "images/kapson/bgp/K-705.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "Model- K705 5kg BGP (with wheel)",
                "price": 1900
            },
            {
                "label": "Model- KGPW-6 6kg BGP (with wheel)",
                "price": 2100
            },
            {
                "label": "Model- K706 10kg BGP (with wheel)",
                "price": 2300
            },
            {
                "label": "Model- K707 15kg BGP (with wheel)",
                "price": 2600
            },
            {
                "label": "Model- K708 20kg BGP (with wheel)",
                "price": 2500
            }
        ]
    },
    {
        "id": 4,
        "name": "Hand Gun",
        "brand": "Kapson",
        "description": "Kapson grease hand gun.Easy to use. Available in multiple capacities.",
        "images": [
            "images/kapson/bgp/K-501.png",
            "images/kapson/bgp/K-506.png",
            "images/kapson/bgp/K-507.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "Model- K513 32OZ / 950CC (5/16 PISTON)",
                "price": 500
            },
            {
                "label": "Model- K501 150Z / 500 CC (5/8 PISTON)",
                "price": 650
            },
            {
                "label": "Model- K503 150Z / 445CC (1/2 PISTON)",
                "price": 780
            },
            {
                "label": "Model- K506 140Z / 500CC (5/16 PISTON)",
                "price": 900
            },
            {
                "label": "Model- K507 100Z / 300CC (5/16 PISTON)",
                "price": 1100
            },
            {
                "label": "Model- K509 80Z / 200CC (5/16 PISTON)",
                "price": 1250
            },
            {
                "label": "Model- K511 80Z / 200CC (5/16 PISTON)",
                "price": 1400
            }
        ]
    },
    {
        "id": 5,
        "name": "Grease Fittings",
        "brand": "Kapson",
        "description": "Fittings for grease gun. Available in multiple capacities.",
        "images": [
            "images/kapson/fitting/K-266.png",
            "images/kapson/fitting/K-267.png",
            "images/kapson/fitting/K-268.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "Model- K326 6.0X1.0MM /STRAIGHT /L-16MM",
                "price": 500
            },
            {
                "label": "Model- K327 6.0X1.0MM /45 DEG /L-21 MM",
                "price": 650
            },
            {
                "label": "Model- K328 6.0X1.0MM /90 DEG /L-18 MM",
                "price": 780
            },
            {
                "label": "Model- K329 8.0X1.0MM /STRAIGHT /L-16MM",
                "price": 500
            },
            {
                "label": "Model- K330 8.0X1.0MM /45 DEG /L-21 MM",
                "price": 650
            },
            {
                "label": "Model- K331 8.0X1.0MM /90 DEG /L-18 MM",
                "price": 780
            },
            {
                "label": "Model- K332 10.0X1.0MM /STRAIGHT/L-18MM",
                "price": 780
            },
            {
                "label": "Model- K333 10.0X1.0MM /45DEG /L-21 MM",
                "price": 780
            },
            {
                "label": "Model- K334 10.0X1.0MM /90DEG /L-18MM",
                "price": 780
            },
            {
                "label": "Model- K335 10.0X1.5MM /STRAIGHT /L-18MM",
                "price": 780
            },
            {
                "label": "Model- K336 10.0X1.5MM /45 DEG /L-21MM",
                "price": 780
            },
            {
                "label": "Model- K337 10.0X1.5MM /90 DEG /L-18MM",
                "price": 780
            }
        ]
    },
    {
        "id": 6,
        "name": "Rotary Pump, Oil Can",
        "brand": "Kapson",
        "description": "Kapson rotary pumps for grease and oil. Easy to use. Available in multiple capacities.",
        "images": [
            "images/kapson/accessories/K-402.png",
            "images/kapson/accessories/K-405.png",
            "images/kapson/accessories/prcp.png",
            "images/kapson/accessories/prop.png",
            "images/kapson/accessories/K-102.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "Rotary Barrel Pump",
                "price": 500
            },
            {
                "label": "Lever Action Barrel Pump",
                "price": 650
            },
            {
                "label": "Plastic Rotary Chemical Pump",
                "price": 780
            },
            {
                "label": "Plastic Rotary Oil Pump",
                "price": 900
            },
            {
                "label": "Oil Can",
                "price": 1100
            }
        ]
    },
    {
        "id": 7,
        "name": "Cantilever Tool Box",
        "brand": "Kapson",
        "description": "Kapson Tool Box. Easy to use. Available in multiple capacities.",
        "images": [
            "images/kapson/accessories/K-600.png",
            "images/kapson/accessories/K-602.png"
        ],
        "bestSeller": false,
        "newArrival": true,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "5 compartments",
                "price": 3000
            }
        ]
    },
    {
        "id": 8,
        "name": "T-Type Socket",
        "brand": "Kapson",
        "description": "Kapson T-Type Socket. Easy to use. Available in multiple capacities.",
        "images": [
            "images/kapson/accessories/K-206.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "6 MM",
                "price": 3000
            },
            {
                "label": "7 MM",
                "price": 3000
            },
            {
                "label": "8 MM",
                "price": 3000
            },
            {
                "label": "9 MM",
                "price": 3000
            },
            {
                "label": "10 MM",
                "price": 3000
            },
            {
                "label": "11 MM",
                "price": 3000
            },
            {
                "label": "12 MM",
                "price": 3000
            },
            {
                "label": "13 MM",
                "price": 3000
            },
            {
                "label": "14 MM",
                "price": 3000
            },
            {
                "label": "15 MM",
                "price": 3000
            },
            {
                "label": "16 MM",
                "price": 3000
            },
            {
                "label": "17 MM",
                "price": 3000
            },
            {
                "label": "18 MM",
                "price": 3000
            },
            {
                "label": "19 MM",
                "price": 3000
            }
        ]
    },
    {
        "id": 9,
        "name": "Hose Pipe, Hose",
        "brand": "Kapson",
        "description": "Kapson Hose Pipe. Easy to use. Available in multiple capacities.",
        "images": [
            "images/kapson/accessories/K-174.png",
            "images/kapson/accessories/K-130.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "Hose Pipe W/o Gun",
                "price": 3000
            },
            {
                "label": "Hose Pipe With Gun",
                "price": 3000
            },
            {
                "label": "Hose 12'",
                "price": 3000
            },
            {
                "label": "Hose 18'",
                "price": 3000
            }
        ]
    },
    {
        "id": 10,
        "name": "Wheel Spanner",
        "brand": "Kapson",
        "description": "Kapson Wheel Spanner. Easy to use. Available in multiple capacities.",
        "images": [
            "images/kapson/accessories/K-951.png"
        ],
        "bestSeller": false,
        "newArrival": true,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "K-951 24x24",
                "price": 3000
            },
            {
                "label": "K-952 24x24",
                "price": 3000
            },
            {
                "label": "K-953 24x24",
                "price": 3000
            },
            {
                "label": "K-954 24x24",
                "price": 3000
            },
            {
                "label": "K-955 24x24",
                "price": 3000
            },
            {
                "label": "K-956 24x24",
                "price": 3000
            },
            {
                "label": "K-957 24x24",
                "price": 3000
            },
            {
                "label": "K-958 24x24",
                "price": 3000
            },
            {
                "label": "K-959 24x24",
                "price": 3000
            },
            {
                "label": "K-960 24x24",
                "price": 3000
            },
            {
                "label": "K-960 24x24",
                "price": 3000
            },
            {
                "label": "K-961 24x24",
                "price": 3000
            },
            {
                "label": "K-962 24x24",
                "price": 3000
            },
            {
                "label": "K-963 24x24",
                "price": 3000
            },
            {
                "label": "K-964 24x24",
                "price": 3000
            },
            {
                "label": "K-965 24x24",
                "price": 3000
            },
            {
                "label": "K-966 24x24",
                "price": 3000
            },
            {
                "label": "K-967 24x24",
                "price": 3000
            },
            {
                "label": "K-968 24x24",
                "price": 3000
            },
            {
                "label": "K-969 24x24",
                "price": 3000
            },
            {
                "label": "K-970 24x24",
                "price": 3000
            },
            {
                "label": "K-971 24x24",
                "price": 3000
            },
            {
                "label": "K-972 24x24",
                "price": 3000
            },
            {
                "label": "K-973 24x24",
                "price": 3000
            }
        ]
    },
    {
        "id": 11,
        "name": "Nozzles",
        "brand": "Kapson",
        "description": "Kapson Coupler And Nozzles. Pencil type nozzles. Available in multiple capacities.",
        "images": [
            "images/kapson/nozzel/K-278.png",
            "images/kapson/nozzel/K-381.png",
            "images/kapson/nozzel/K-382.png",
            "images/kapson/nozzel/K-383.png",
            "images/kapson/nozzel/K-384.png",
            "images/kapson/nozzel/K-385.png",
            "images/kapson/nozzel/K-386.png",
            "images/kapson/nozzel/K-388.png"
        ],
        "bestSeller": false,
        "newArrival": true,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "K-278 Coupler",
                "price": 3000
            },
            {
                "label": "Pencil Nozzles",
                "price": 3000
            }
        ]
    },
    {
        "id": 21,
        "name": "Hand Operated Grease Dispenser(Pump)",
        "brand": "Penta",
        "description": "Penta hand operated grease dispenser . Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/hod/hod2.jpg",
            "images/penta/hod/hod3.png",
            "images/penta/hod/hod4.jpg",
            "images/penta/hod/hod5.jpg",
            "images/penta/hod/hod6.png",
            "images/penta/hod/hod7.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "3kg",
                "price": 3200
            },
            {
                "label": "5kg",
                "price": 3900
            },
            {
                "label": "10kg",
                "price": 4600
            },
            {
                "label": "20kg",
                "price": 4600
            }
        ]
    },
    {
        "id": 22,
        "name": "Pneumatic Grease Dispenser(Pump)",
        "brand": "Penta",
        "description": "Penta pneumatic grease dispenser . Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/pgd/pgd1.png",
            "images/penta/pgd/pgd2.png",
            "images/penta/pgd/pgd3.png",
            "images/penta/pgd/pgd4.png",
            "images/penta/pgd/pgd5.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "5kg",
                "price": 3200
            },
            {
                "label": "15kg",
                "price": 3900
            },
            {
                "label": "25kg",
                "price": 4600
            },
            {
                "label": "50kg",
                "price": 4600
            }
        ]
    },
    {
        "id": 23,
        "name": "Pneumatic Oil Dispenser(Pump)",
        "brand": "Penta",
        "description": "Penta pneumatic oil dispenser . Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/pod.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "50kg",
                "price": 3200
            }
        ]
    },
    {
        "id": 24,
        "name": "Hydraulic Floor Crane",
        "brand": "Penta",
        "description": "Penta hydraulic floor crane. Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/hfc1.png",
            "images/penta/hfc2.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "1.25 Ton",
                "price": 3200
            },
            {
                "label": "2 Ton",
                "price": 3200
            }
        ]
    },
    {
        "id": 25,
        "name": "Hydraulic Trolley Jack",
        "brand": "Penta",
        "description": "Penta hydraulic Trolley Jack. Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/htj1.png",
            "images/penta/htj3.png",
            "images/penta/htj4.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "3 Ton Regular",
                "price": 3200
            },
            {
                "label": "3 Ton Low Profile",
                "price": 3200
            },
            {
                "label": "5 Ton",
                "price": 3200
            },
            {
                "label": "10 Ton",
                "price": 3200
            }
        ]
    },
    {
        "id": 26,
        "name": "Hydraulic Two Wheeler Lift",
        "brand": "Penta",
        "description": "Penta hydraulic Two Wheeler Lift. Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/hwl.jpg",
            "images/penta/hwl1.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "125kg Manual",
                "price": 3200
            },
            {
                "label": "175kg Manual",
                "price": 3200
            },
            {
                "label": "175kg Motorised",
                "price": 3200
            },
            {
                "label": "300kg Motorised",
                "price": 3200
            }
        ]
    },
    {
        "id": 27,
        "name": "Mechanic Creeper",
        "brand": "Penta",
        "description": "Penta Mechanical Creeper. Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/mc.jpg",
            "images/penta/mc1.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "Regular (90kg load) ",
                "price": 3200
            },
            {
                "label": "Foldable (90kg load)",
                "price": 3200
            }
        ]
    },
    {
        "id": 28,
        "name": "Horizontal Pressure Washer",
        "brand": "Penta",
        "description": "Penta Horizontal Pressure washer. Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/hpw.jpg",
            "images/penta/hpw1.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "X1-A",
                "price": 3200
            },
            {
                "label": "X3-B",
                "price": 3200
            }
        ]
    },
    {
        "id": 29,
        "name": "High Pressure Washer Triplex Pump",
        "brand": "Penta",
        "description": "Penta high pressure washer. Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/highpw.jpg",
            "images/penta/highpw1.jpg",
            "images/penta/highpw2.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "PE50",
                "price": 3200
            },
            {
                "label": "PE100",
                "price": 3200
            },
            {
                "label": "PE200",
                "price": 3200
            },
            {
                "label": "PE300",
                "price": 3200
            }
        ]
    },
    {
        "id": 30,
        "name": "Foam Sprayer",
        "brand": "Penta",
        "description": "Penta high pressure washer. Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/fs.png",
            "images/penta/fs1.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "2 ltr Capacity",
                "price": 3200
            },
            {
                "label": "50 ltr Capacity",
                "price": 3200
            }
        ]
    },
    {
        "id": 31,
        "name": "Axel Stand",
        "brand": "Penta",
        "description": "Penta axel stand. Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/as.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "2 Ton",
                "price": 3200
            },
            {
                "label": "3 Ton",
                "price": 3200
            },
            {
                "label": "6 Ton",
                "price": 3200
            },
            {
                "label": "12 Ton",
                "price": 3200
            },
            {
                "label": "22 Ton",
                "price": 3200
            }
        ]
    },
    {
        "id": 32,
        "name": "Rotary Engine Stand",
        "brand": "Penta",
        "description": "Penta high pressure washer. Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/res.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "",
                "price": 3200
            }
        ]
    },
    {
        "id": 33,
        "name": "Pneumatic Barrel Oil & Grease Pump",
        "brand": "Penta",
        "description": "Penta high pressure washer. Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/pbop.jpg",
            "images/penta/pbgp.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "Oil Pump Capacity = 205kg",
                "price": 3200
            },
            {
                "label": "Grease Pump Capacity = 200ltr",
                "price": 3200
            }
        ]
    },
    {
        "id": 34,
        "name": "Waste Oil Collector",
        "brand": "Penta",
        "description": "Penta high pressure washer. Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/wocm.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "Manual = 25ltr",
                "price": 3200
            },
            {
                "label": "Manual = 50ltr",
                "price": 3200
            },
            {
                "label": "Pressurised = 50ltr",
                "price": 3200
            },
            {
                "label": "Pressurised Truck = 50ltr",
                "price": 3200
            }
        ]
    },
    {
        "id": 35,
        "name": "Automobile Special Tools",
        "brand": "Penta",
        "description": "Penta high pressure washer. Precision-engineered for consistent lubrication output at automotive service centres and workshops.",
        "images": [
            "images/penta/ast.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "Send Enquiry or contact us",
                "price": 1
            }
        ]
    },
    {
        "id": 41,
        "name": "Hydraulic Bottle Jack 2 Ton",
        "brand": "Titan",
        "description": "Titan hydraulic floor jack with steel frame and dual-piston pump for fast lifting. Built for everyday garage and workshop use.",
        "images": [
            "images/titan/2sl.jpg",
            "images/titan/2dl.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "2 Ton Single Lift",
                "price": 1600
            },
            {
                "label": "2 Ton Double Lift",
                "price": 2100
            }
        ]
    },
    {
        "id": 42,
        "name": "Hydraulic Bottle Jack 3 Ton",
        "brand": "Titan",
        "description": "Titan heavy-duty bottle jack for trucks, buses, and commercial vehicles. Compact and powerful.",
        "images": [
            "images/titan/3sl.jpg",
            "images/titan/3dl.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "3 Ton Single Lift",
                "price": 3500
            },
            {
                "label": "3 Ton Double Lift",
                "price": 4800
            }
        ]
    },
    {
        "id": 43,
        "name": "Hydraulic Bottle Jack 5 Ton",
        "brand": "Titan",
        "description": "Titan low profile trolley jack with extra-low minimum height. Perfect for sports cars and vehicles with low ground clearance. Smooth swivel casters.",
        "images": [
            "images/titan/5sl.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "price": 4200
    },
    {
        "id": 44,
        "name": "Hydraulic Bottle Jack 8 Ton",
        "brand": "Titan",
        "description": "Titan heavy-duty bottle jack for trucks, buses, and commercial vehicles. Compact and powerful.",
        "images": [
            "images/titan/8sl.jpg",
            "images/titan/8dl.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "8 Ton Single Lift",
                "price": 3500
            },
            {
                "label": "8 Ton Double Lift",
                "price": 4800
            }
        ]
    },
    {
        "id": 45,
        "name": "Hydraulic Bottle Jack 10 Ton",
        "brand": "Titan",
        "description": "Titan low profile trolley jack with extra-low minimum height. Perfect for sports cars and vehicles with low ground clearance. Smooth swivel casters.",
        "images": [
            "images/titan/10.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "price": 4200
    },
    {
        "id": 46,
        "name": "Hydraulic Bottle Jack 15 Ton",
        "brand": "Titan",
        "description": "Titan low profile trolley jack with extra-low minimum height. Perfect for sports cars and vehicles with low ground clearance. Smooth swivel casters.",
        "images": [
            "images/titan/15.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "price": 4200
    },
    {
        "id": 47,
        "name": "Hydraulic Bottle Jack 20 Ton",
        "brand": "Titan",
        "description": "Titan low profile trolley jack with extra-low minimum height. Perfect for sports cars and vehicles with low ground clearance. Smooth swivel casters.",
        "images": [
            "images/titan/20.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "price": 4200
    },
    {
        "id": 48,
        "name": "Hydraulic Bottle Jack 35 Ton",
        "brand": "Titan",
        "description": "Titan low profile trolley jack with extra-low minimum height. Perfect for sports cars and vehicles with low ground clearance. Smooth swivel casters.",
        "images": [
            "images/titan/35.jpg"
        ],
        "bestSeller": false,
        "newArrival": false,
        "price": 4200
    },
    {
        "id": 49,
        "name": "Hydraulic Floor Jack",
        "brand": "Titan",
        "description": "Titan heavy-duty bottle jack for trucks, buses, and commercial vehicles. Compact and powerful.",
        "images": [
            "images/titan/2fj.jpg",
            "images/titan/3fj.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "2 Ton Hyd Floor Jack",
                "price": 3500
            },
            {
                "label": "3 Ton Hyd Floor Jack",
                "price": 4800
            }
        ]
    },
    {
        "id": 50,
        "name": "Wheel Choke & Jack Stand",
        "brand": "Titan",
        "description": "Titan heavy-duty bottle jack for trucks, buses, and commercial vehicles. Compact and powerful.",
        "images": [
            "images/titan/wc.png",
            "images/titan/js.png"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Capacity",
        "variants": [
            {
                "label": "Wheel Choke",
                "price": 3500
            },
            {
                "label": "Jack Stand",
                "price": 4800
            }
        ]
    },
    {
        "id": 130,
        "name": "Combination Spanner",
        "brand": "Groz",
        "description": "Groz combination spanner — chrome vanadium steel, precision forged and heat-treated. 15° offset ring end for knuckle clearance. Individual sizes or full set.",
        "images": [
            "https://via.placeholder.com/400x300?text=Groz+Spanner",
            "https://via.placeholder.com/400x300?text=Groz+Spanner+Set",
            "https://via.placeholder.com/400x300?text=Groz+Spanner+Detail"
        ],
        "bestSeller": true,
        "newArrival": false,
        "variantType": "Size",
        "variants": [
            {
                "label": "8mm",
                "price": 85
            },
            {
                "label": "10mm",
                "price": 90
            },
            {
                "label": "12mm",
                "price": 100
            },
            {
                "label": "14mm",
                "price": 110
            },
            {
                "label": "17mm",
                "price": 130
            },
            {
                "label": "19mm",
                "price": 150
            },
            {
                "label": "22mm",
                "price": 180
            },
            {
                "label": "Set 8 Pcs",
                "price": 850
            }
        ]
    },
    {
        "id": 14,
        "name": "Torque Wrench",
        "brand": "Groz",
        "description": "Groz click-type torque wrench. Dual-direction ratchet, adjustable torque range. Audible click on correct torque. Storage case included.",
        "images": [
            "https://via.placeholder.com/400x300?text=Groz+Torque+Wrench",
            "https://via.placeholder.com/400x300?text=Torque+Scale+Detail",
            "https://via.placeholder.com/400x300?text=Torque+Head+Detail"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Drive Size",
        "variants": [
            {
                "label": "1/4\"  —  5–25 Nm",
                "price": 1200
            },
            {
                "label": "3/8\"  — 20–110 Nm",
                "price": 1500
            },
            {
                "label": "1/2\"  — 40–210 Nm",
                "price": 1800
            },
            {
                "label": "3/4\"  — 100–500 Nm",
                "price": 3200
            }
        ]
    },
    {
        "id": 15,
        "name": "Grease Gun",
        "brand": "Groz",
        "description": "Groz professional grease gun. Compatible with 400g cartridges. High-pressure output for hard-to-reach fittings. Available in lever, pistol, and mini types.",
        "images": [
            "https://via.placeholder.com/400x300?text=Groz+Grease+Gun",
            "https://via.placeholder.com/400x300?text=Grease+Gun+Nozzle"
        ],
        "bestSeller": true,
        "newArrival": false,
        "variantType": "Type",
        "variants": [
            {
                "label": "Lever Type",
                "price": 650
            },
            {
                "label": "Pistol Type",
                "price": 850
            },
            {
                "label": "Mini Type",
                "price": 480
            },
            {
                "label": "Flexible Hose (Extra)",
                "price": 220
            }
        ]
    },
    {
        "id": 16,
        "name": "Extension Bar (Socket Drive)",
        "brand": "Groz",
        "description": "Groz chrome vanadium extension bar. Knurled grip for easy handling. Fits all standard socket sets. Multiple drive sizes and lengths available.",
        "images": [
            "https://via.placeholder.com/400x300?text=Groz+Extension+Bar",
            "https://via.placeholder.com/400x300?text=Extension+Bar+End"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Size & Drive",
        "variants": [
            {
                "label": "1/4\"  75mm",
                "price": 180
            },
            {
                "label": "1/4\" 150mm",
                "price": 220
            },
            {
                "label": "3/8\"  75mm",
                "price": 220
            },
            {
                "label": "3/8\" 150mm",
                "price": 260
            },
            {
                "label": "3/8\" 250mm",
                "price": 310
            },
            {
                "label": "1/2\" 125mm",
                "price": 280
            },
            {
                "label": "1/2\" 250mm",
                "price": 350
            },
            {
                "label": "1/2\" 450mm",
                "price": 480
            }
        ]
    },
    {
        "id": 17,
        "name": "Ratchet Handle",
        "brand": "Groz",
        "description": "Groz quick-release ratchet handle. 72-tooth mechanism for fine movement in tight spaces. Comfort grip. Available in 1/4\", 3/8\", and 1/2\" drive.",
        "images": [
            "https://via.placeholder.com/400x300?text=Groz+Ratchet",
            "https://via.placeholder.com/400x300?text=Ratchet+Head+Detail"
        ],
        "bestSeller": false,
        "newArrival": true,
        "variantType": "Drive Size",
        "variants": [
            {
                "label": "1/4 inch",
                "price": 380
            },
            {
                "label": "3/8 inch",
                "price": 480
            },
            {
                "label": "1/2 inch",
                "price": 620
            }
        ]
    },
    {
        "id": 18,
        "name": "Socket Set",
        "brand": "Hand Tools",
        "description": "Complete socket set with metric sockets, ratchet handle, and extension bars in a blow-moulded carry case.",
        "images": [
            "https://via.placeholder.com/400x300?text=Socket+Set",
            "https://via.placeholder.com/400x300?text=Socket+Set+Open"
        ],
        "bestSeller": true,
        "newArrival": false,
        "variantType": "Piece Count",
        "variants": [
            {
                "label": "40 Pcs — 1/4\" & 1/2\"",
                "price": 1200
            },
            {
                "label": "72 Pcs — 1/4\", 3/8\" & 1/2\"",
                "price": 2100
            },
            {
                "label": "94 Pcs — Full Pro Set",
                "price": 3200
            }
        ]
    },
    {
        "id": 19,
        "name": "Ball Peen Hammer",
        "brand": "Hand Tools",
        "description": "Drop-forged steel ball peen hammer with hardwood handle. Heat-treated head for lasting durability.",
        "images": [
            "https://via.placeholder.com/400x300?text=Ball+Peen+Hammer"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Weight",
        "variants": [
            {
                "label": "250g",
                "price": 180
            },
            {
                "label": "500g",
                "price": 280
            },
            {
                "label": "1kg",
                "price": 420
            }
        ]
    },
    {
        "id": 200,
        "name": "Plier Set",
        "brand": "Hand Tools",
        "description": "Chrome vanadium steel plier set. Includes combination, long nose, and cutting pliers with bi-material comfort grip handles.",
        "images": [
            "https://via.placeholder.com/400x300?text=Plier+Set",
            "https://via.placeholder.com/400x300?text=Plier+Detail"
        ],
        "bestSeller": false,
        "newArrival": false,
        "variantType": "Set Size",
        "variants": [
            {
                "label": "3 Pcs",
                "price": 450
            },
            {
                "label": "5 Pcs",
                "price": 720
            }
        ]
    },
    {
        "id": 210,
        "name": "Angle Grinder",
        "brand": "Power Tools",
        "description": "Heavy-duty angle grinder with safety guard, spindle lock, and anti-restart protection. For grinding, cutting, and polishing metal.",
        "images": [
            "https://via.placeholder.com/400x300?text=Angle+Grinder",
            "https://via.placeholder.com/400x300?text=Grinder+Guard+Detail",
            "https://via.placeholder.com/400x300?text=Grinder+Disc+Side"
        ],
        "bestSeller": true,
        "newArrival": false,
        "variantType": "Disc Size",
        "variants": [
            {
                "label": "4 inch — 850W",
                "price": 2200
            },
            {
                "label": "5 inch — 1050W",
                "price": 2800
            },
            {
                "label": "7 inch — 1800W",
                "price": 4200
            }
        ]
    },
    {
        "id": 220,
        "name": "Electric Drill",
        "brand": "Power Tools",
        "description": "Variable speed electric drill with keyless chuck. Forward/reverse rotation. For drilling metal, wood, and concrete.",
        "images": [
            "https://via.placeholder.com/400x300?text=Electric+Drill",
            "https://via.placeholder.com/400x300?text=Drill+Chuck+Detail"
        ],
        "bestSeller": false,
        "newArrival": true,
        "variantType": "Chuck Size",
        "variants": [
            {
                "label": "10mm — 500W",
                "price": 1500
            },
            {
                "label": "13mm — 750W",
                "price": 1900
            },
            {
                "label": "13mm — 1050W (Impact)",
                "price": 2800
            }
        ]
    },
    {
        "id": 221,
        "name": "L handle",
        "brand": "Hand Tools",
        "bestSeller": false,
        "newArrival": false,
        "variantType": "size",
        "price": 0
    }
];
